[package]
name = "lac"
version = "0.1.0"
authors = ["samo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9"
hex = "0.4"
hound = "3.4"
claxon = "0.4"
argh = "0.1"
num_cpus = "1.13"
async-std = "1.9.0"